package helperdata

import (
	"github.com/cilium/ebpf/asm"
	"strings"
)

// Code generated by 'go run cmd/gen/helperdata.go | gofmt > pkg/helperdata/helperdata.go' DO NOT EDIT

type HelperFunc struct {
	RetType CType
	Params  []HelperParam
}

type HelperParam struct {
	Type CType
	Name string
}

type CType struct {
	Name   string
	Ptr    bool
	Const  bool
	Struct bool
}

func (c CType) String() string {
	var parts []string
	if c.Const {
		parts = append(parts, "const")
	}

	if c.Struct {
		parts = append(parts, "struct")
	}

	parts = append(parts, c.Name)

	if c.Ptr {
		parts = append(parts, "*")
	}

	return strings.Join(parts, " ")
}

var Signatures = map[asm.BuiltinFunc]HelperFunc{
	asm.FnMapLookupElem: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "key"},
		},
	},
	asm.FnMapUpdateElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "key"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "value"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnMapDeleteElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "key"},
		},
	},
	asm.FnProbeRead: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnKtimeGetNs: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnTracePrintk: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "fmt"},
			{Type: CType{Name: "__u32"}, Name: "fmt_size"},
			{Type: CType{Name: "..."}, Name: ""},
		},
	},
	asm.FnGetPrandomU32: {
		RetType: CType{Name: "__u32"},
		Params:  []HelperParam{},
	},
	asm.FnGetSmpProcessorId: {
		RetType: CType{Name: "__u32"},
		Params:  []HelperParam{},
	},
	asm.FnSkbStoreBytes: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "from"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnL3CsumReplace: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "__u64"}, Name: "from"},
			{Type: CType{Name: "__u64"}, Name: "to"},
			{Type: CType{Name: "__u64"}, Name: "size"},
		},
	},
	asm.FnL4CsumReplace: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "__u64"}, Name: "from"},
			{Type: CType{Name: "__u64"}, Name: "to"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTailCall: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "prog_array_map"},
			{Type: CType{Name: "__u32"}, Name: "index"},
		},
	},
	asm.FnCloneRedirect: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "ifindex"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnGetCurrentPidTgid: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnGetCurrentUidGid: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnGetCurrentComm: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "size_of_buf"},
		},
	},
	asm.FnGetCgroupClassid: {
		RetType: CType{Name: "__u32"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnSkbVlanPush: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__be16"}, Name: "vlan_proto"},
			{Type: CType{Name: "__u16"}, Name: "vlan_tci"},
		},
	},
	asm.FnSkbVlanPop: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnSkbGetTunnelKey: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "bpf_tunnel_key", Struct: true, Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbSetTunnelKey: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "bpf_tunnel_key", Struct: true, Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnPerfEventRead: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRedirect: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "ifindex"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnGetRouteRealm: {
		RetType: CType{Name: "__u32"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnPerfEventOutput: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "size"},
		},
	},
	asm.FnSkbLoadBytes: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Ptr: true}, Name: "to"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnGetStackid: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnCsumDiff: {
		RetType: CType{Name: "__s64"},
		Params: []HelperParam{
			{Type: CType{Name: "__be32", Ptr: true}, Name: "from"},
			{Type: CType{Name: "__u32"}, Name: "from_size"},
			{Type: CType{Name: "__be32", Ptr: true}, Name: "to"},
			{Type: CType{Name: "__u32"}, Name: "to_size"},
			{Type: CType{Name: "__wsum"}, Name: "seed"},
		},
	},
	asm.FnSkbGetTunnelOpt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "void", Ptr: true}, Name: "opt"},
			{Type: CType{Name: "__u32"}, Name: "size"},
		},
	},
	asm.FnSkbSetTunnelOpt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "void", Ptr: true}, Name: "opt"},
			{Type: CType{Name: "__u32"}, Name: "size"},
		},
	},
	asm.FnSkbChangeProto: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__be16"}, Name: "proto"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbChangeType: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "type"},
		},
	},
	asm.FnSkbUnderCgroup: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u32"}, Name: "index"},
		},
	},
	asm.FnGetHashRecalc: {
		RetType: CType{Name: "__u32"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnGetCurrentTask: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnProbeWriteUser: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "src"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnCurrentTaskUnderCgroup: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u32"}, Name: "index"},
		},
	},
	asm.FnSkbChangeTail: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbPullData: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnCsumUpdate: {
		RetType: CType{Name: "__s64"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__wsum"}, Name: "csum"},
		},
	},
	asm.FnSetHashInvalid: {
		RetType: CType{Name: "void"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnGetNumaNodeId: {
		RetType: CType{Name: "long"},
		Params:  []HelperParam{},
	},
	asm.FnSkbChangeHead: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnXdpAdjustHead: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
			{Type: CType{Name: "int"}, Name: "delta"},
		},
	},
	asm.FnProbeReadStr: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnGetSocketCookie: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.FnGetSocketUid: {
		RetType: CType{Name: "__u32"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnSetHash: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "hash"},
		},
	},
	asm.FnSetsockopt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "bpf_socket"},
			{Type: CType{Name: "int"}, Name: "level"},
			{Type: CType{Name: "int"}, Name: "optname"},
			{Type: CType{Name: "void", Ptr: true}, Name: "optval"},
			{Type: CType{Name: "int"}, Name: "optlen"},
		},
	},
	asm.FnSkbAdjustRoom: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__s32"}, Name: "len_diff"},
			{Type: CType{Name: "__u32"}, Name: "mode"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRedirectMap: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u32"}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkRedirectMap: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u32"}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSockMapUpdate: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "skops"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnXdpAdjustMeta: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
			{Type: CType{Name: "int"}, Name: "delta"},
		},
	},
	asm.FnPerfEventReadValue: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "bpf_perf_event_value", Struct: true, Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "buf_size"},
		},
	},
	asm.FnPerfProgReadValue: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_perf_event_data", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "bpf_perf_event_value", Struct: true, Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "buf_size"},
		},
	},
	asm.FnGetsockopt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "bpf_socket"},
			{Type: CType{Name: "int"}, Name: "level"},
			{Type: CType{Name: "int"}, Name: "optname"},
			{Type: CType{Name: "void", Ptr: true}, Name: "optval"},
			{Type: CType{Name: "int"}, Name: "optlen"},
		},
	},
	asm.FnOverrideReturn: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "pt_regs", Struct: true, Ptr: true}, Name: "regs"},
			{Type: CType{Name: "__u64"}, Name: "rc"},
		},
	},
	asm.FnSockOpsCbFlagsSet: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "bpf_sock"},
			{Type: CType{Name: "int"}, Name: "argval"},
		},
	},
	asm.FnMsgRedirectMap: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u32"}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnMsgApplyBytes: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "__u32"}, Name: "bytes"},
		},
	},
	asm.FnMsgCorkBytes: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "__u32"}, Name: "bytes"},
		},
	},
	asm.FnMsgPullData: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "__u32"}, Name: "start"},
			{Type: CType{Name: "__u32"}, Name: "end"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnBind: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_addr", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "sockaddr", Struct: true, Ptr: true}, Name: "addr"},
			{Type: CType{Name: "int"}, Name: "addr_len"},
		},
	},
	asm.FnXdpAdjustTail: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
			{Type: CType{Name: "int"}, Name: "delta"},
		},
	},
	asm.FnSkbGetXfrmState: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "index"},
			{Type: CType{Name: "bpf_xfrm_state", Struct: true, Ptr: true}, Name: "xfrm_state"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnGetStack: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbLoadBytesRelative: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Ptr: true}, Name: "to"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u32"}, Name: "start_header"},
		},
	},
	asm.FnFibLookup: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "bpf_fib_lookup", Struct: true, Ptr: true}, Name: "params"},
			{Type: CType{Name: "int"}, Name: "plen"},
			{Type: CType{Name: "__u32"}, Name: "flags"},
		},
	},
	asm.FnSockHashUpdate: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "skops"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnMsgRedirectHash: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkRedirectHash: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnLwtPushEncap: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "type"},
			{Type: CType{Name: "void", Ptr: true}, Name: "hdr"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnLwtSeg6StoreBytes: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "from"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnLwtSeg6AdjustSrh: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "__s32"}, Name: "delta"},
		},
	},
	asm.FnLwtSeg6Action: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u32"}, Name: "action"},
			{Type: CType{Name: "void", Ptr: true}, Name: "param"},
			{Type: CType{Name: "__u32"}, Name: "param_len"},
		},
	},
	asm.FnRcRepeat: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.FnRcKeydown: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "__u32"}, Name: "protocol"},
			{Type: CType{Name: "__u64"}, Name: "scancode"},
			{Type: CType{Name: "__u32"}, Name: "toggle"},
		},
	},
	asm.FnSkbCgroupId: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnGetCurrentCgroupId: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnGetLocalStorage: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkSelectReuseport: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_reuseport_md", Struct: true, Ptr: true}, Name: "reuse"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "key"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbAncestorCgroupId: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "int"}, Name: "ancestor_level"},
		},
	},
	asm.FnSkLookupTcp: {
		RetType: CType{Name: "bpf_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "bpf_sock_tuple", Struct: true, Ptr: true}, Name: "tuple"},
			{Type: CType{Name: "__u32"}, Name: "tuple_size"},
			{Type: CType{Name: "__u64"}, Name: "netns"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkLookupUdp: {
		RetType: CType{Name: "bpf_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "bpf_sock_tuple", Struct: true, Ptr: true}, Name: "tuple"},
			{Type: CType{Name: "__u32"}, Name: "tuple_size"},
			{Type: CType{Name: "__u64"}, Name: "netns"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkRelease: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sock"},
		},
	},
	asm.FnMapPushElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "value"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnMapPopElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "value"},
		},
	},
	asm.FnMapPeekElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "value"},
		},
	},
	asm.FnMsgPushData: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "__u32"}, Name: "start"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnMsgPopData: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "sk_msg_md", Struct: true, Ptr: true}, Name: "msg"},
			{Type: CType{Name: "__u32"}, Name: "start"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRcPointerRel: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "__s32"}, Name: "rel_x"},
			{Type: CType{Name: "__s32"}, Name: "rel_y"},
		},
	},
	asm.FnSpinLock: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_spin_lock", Struct: true, Ptr: true}, Name: "lock"},
		},
	},
	asm.FnSpinUnlock: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_spin_lock", Struct: true, Ptr: true}, Name: "lock"},
		},
	},
	asm.FnSkFullsock: {
		RetType: CType{Name: "bpf_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock", Struct: true, Ptr: true}, Name: "sk"},
		},
	},
	asm.FnTcpSock: {
		RetType: CType{Name: "bpf_tcp_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock", Struct: true, Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkbEcnSetCe: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnGetListenerSock: {
		RetType: CType{Name: "bpf_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock", Struct: true, Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkcLookupTcp: {
		RetType: CType{Name: "bpf_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "bpf_sock_tuple", Struct: true, Ptr: true}, Name: "tuple"},
			{Type: CType{Name: "__u32"}, Name: "tuple_size"},
			{Type: CType{Name: "__u64"}, Name: "netns"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTcpCheckSyncookie: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
			{Type: CType{Name: "void", Ptr: true}, Name: "iph"},
			{Type: CType{Name: "__u32"}, Name: "iph_len"},
			{Type: CType{Name: "tcphdr", Struct: true, Ptr: true}, Name: "th"},
			{Type: CType{Name: "__u32"}, Name: "th_len"},
		},
	},
	asm.FnSysctlGetName: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sysctl", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "char", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSysctlGetCurrentValue: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sysctl", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "char", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
		},
	},
	asm.FnSysctlGetNewValue: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sysctl", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "char", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
		},
	},
	asm.FnSysctlSetNewValue: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sysctl", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
		},
	},
	asm.FnStrtol: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "long", Ptr: true}, Name: "res"},
		},
	},
	asm.FnStrtoul: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "buf"},
			{Type: CType{Name: "unsigned"}, Name: "buf_len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "unsigned"}, Name: "res"},
		},
	},
	asm.FnSkStorageGet: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
			{Type: CType{Name: "void", Ptr: true}, Name: "value"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkStorageDelete: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSendSignal: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "sig"},
		},
	},
	asm.FnTcpGenSyncookie: {
		RetType: CType{Name: "__s64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
			{Type: CType{Name: "void", Ptr: true}, Name: "iph"},
			{Type: CType{Name: "__u32"}, Name: "iph_len"},
			{Type: CType{Name: "tcphdr", Struct: true, Ptr: true}, Name: "th"},
			{Type: CType{Name: "__u32"}, Name: "th_len"},
		},
	},
	asm.FnSkbOutput: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "size"},
		},
	},
	asm.FnProbeReadUser: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnProbeReadKernel: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnProbeReadUserStr: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnProbeReadKernelStr: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "unsafe_ptr"},
		},
	},
	asm.FnTcpSendAck: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "tp"},
			{Type: CType{Name: "__u32"}, Name: "rcv_nxt"},
		},
	},
	asm.FnSendSignalThread: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "sig"},
		},
	},
	asm.FnJiffies64: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnReadBranchRecords: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_perf_event_data", Struct: true, Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnGetNsCurrentPidTgid: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u64"}, Name: "dev"},
			{Type: CType{Name: "__u64"}, Name: "ino"},
			{Type: CType{Name: "bpf_pidns_info", Struct: true, Ptr: true}, Name: "nsdata"},
			{Type: CType{Name: "__u32"}, Name: "size"},
		},
	},
	asm.FnXdpOutput: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "size"},
		},
	},
	asm.FnGetNetnsCookie: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.FnGetCurrentAncestorCgroupId: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "int"}, Name: "ancestor_level"},
		},
	},
	asm.FnSkAssign: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnKtimeGetBootNs: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnSeqPrintf: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "seq_file", Struct: true, Ptr: true}, Name: "m"},
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "fmt"},
			{Type: CType{Name: "__u32"}, Name: "fmt_size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u32"}, Name: "data_len"},
		},
	},
	asm.FnSeqWrite: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "seq_file", Struct: true, Ptr: true}, Name: "m"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.FnSkCgroupId: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkAncestorCgroupId: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
			{Type: CType{Name: "int"}, Name: "ancestor_level"},
		},
	},
	asm.FnRingbufOutput: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ringbuf"},
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRingbufReserve: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ringbuf"},
			{Type: CType{Name: "__u64"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRingbufSubmit: {
		RetType: CType{Name: "void"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRingbufDiscard: {
		RetType: CType{Name: "void"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnRingbufQuery: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ringbuf"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnCsumLevel: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
			{Type: CType{Name: "__u64"}, Name: "level"},
		},
	},
	asm.FnSkcToTcp6Sock: {
		RetType: CType{Name: "tcp6_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkcToTcpSock: {
		RetType: CType{Name: "tcp_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkcToTcpTimewaitSock: {
		RetType: CType{Name: "tcp_timewait_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkcToTcpRequestSock: {
		RetType: CType{Name: "tcp_request_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnSkcToUdp6Sock: {
		RetType: CType{Name: "udp6_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.FnGetTaskStack: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "task"},
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnLoadHdrOpt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "skops"},
			{Type: CType{Name: "void", Ptr: true}, Name: "searchby_res"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnStoreHdrOpt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "skops"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "from"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnReserveHdrOpt: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_sock_ops", Struct: true, Ptr: true}, Name: "skops"},
			{Type: CType{Name: "__u32"}, Name: "len"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnInodeStorageGet: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "inode"},
			{Type: CType{Name: "void", Ptr: true}, Name: "value"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnInodeStorageDelete: {
		RetType: CType{Name: "int"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "inode"},
		},
	},
	asm.FnDPath: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "path", Struct: true, Ptr: true}, Name: "path"},
			{Type: CType{Name: "char", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "sz"},
		},
	},
	asm.FnCopyFromUser: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "user_ptr"},
		},
	},
	asm.FnSnprintfBtf: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Ptr: true}, Name: "str"},
			{Type: CType{Name: "__u32"}, Name: "str_size"},
			{Type: CType{Name: "btf_ptr", Struct: true, Ptr: true}, Name: "ptr"},
			{Type: CType{Name: "__u32"}, Name: "btf_ptr_size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSeqPrintfBtf: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "seq_file", Struct: true, Ptr: true}, Name: "m"},
			{Type: CType{Name: "btf_ptr", Struct: true, Ptr: true}, Name: "ptr"},
			{Type: CType{Name: "__u32"}, Name: "ptr_size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSkbCgroupClassid: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "__sk_buff", Struct: true, Ptr: true}, Name: "skb"},
		},
	},
	asm.FnRedirectNeigh: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "ifindex"},
			{Type: CType{Name: "bpf_redir_neigh", Struct: true, Ptr: true}, Name: "params"},
			{Type: CType{Name: "int"}, Name: "plen"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnPerCpuPtr: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "percpu_ptr"},
			{Type: CType{Name: "__u32"}, Name: "cpu"},
		},
	},
	asm.FnThisCpuPtr: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "percpu_ptr"},
		},
	},
	asm.FnRedirectPeer: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "ifindex"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTaskStorageGet: {
		RetType: CType{Name: "void", Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "task"},
			{Type: CType{Name: "void", Ptr: true}, Name: "value"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTaskStorageDelete: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "task"},
		},
	},
	asm.FnGetCurrentTaskBtf: {
		RetType: CType{Name: "task_struct", Struct: true, Ptr: true},
		Params:  []HelperParam{},
	},
	asm.FnBprmOptsSet: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "linux_binprm", Struct: true, Ptr: true}, Name: "bprm"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnKtimeGetCoarseNs: {
		RetType: CType{Name: "__u64"},
		Params:  []HelperParam{},
	},
	asm.FnImaInodeHash: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "inode", Struct: true, Ptr: true}, Name: "inode"},
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
		},
	},
	asm.FnSockFromFile: {
		RetType: CType{Name: "socket", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "file", Struct: true, Ptr: true}, Name: "file"},
		},
	},
	asm.FnCheckMtu: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "__u32"}, Name: "ifindex"},
			{Type: CType{Name: "__u32", Ptr: true}, Name: "mtu_len"},
			{Type: CType{Name: "__s32"}, Name: "len_diff"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnForEachMapElem: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_fn"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_ctx"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnSnprintf: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Ptr: true}, Name: "str"},
			{Type: CType{Name: "__u32"}, Name: "str_size"},
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "fmt"},
			{Type: CType{Name: "__u64", Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u32"}, Name: "data_len"},
		},
	},
	asm.FnSysBpf: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "cmd"},
			{Type: CType{Name: "void", Ptr: true}, Name: "attr"},
			{Type: CType{Name: "__u32"}, Name: "attr_size"},
		},
	},
	asm.FnBtfFindByNameKind: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Ptr: true}, Name: "name"},
			{Type: CType{Name: "int"}, Name: "name_sz"},
			{Type: CType{Name: "__u32"}, Name: "kind"},
			{Type: CType{Name: "int"}, Name: "flags"},
		},
	},
	asm.FnSysClose: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "fd"},
		},
	},
	asm.FnTimerInit: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_timer", Struct: true, Ptr: true}, Name: "timer"},
			{Type: CType{Name: "void", Ptr: true}, Name: "map"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTimerSetCallback: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_timer", Struct: true, Ptr: true}, Name: "timer"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_fn"},
		},
	},
	asm.FnTimerStart: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_timer", Struct: true, Ptr: true}, Name: "timer"},
			{Type: CType{Name: "__u64"}, Name: "nsecs"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.FnTimerCancel: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "bpf_timer", Struct: true, Ptr: true}, Name: "timer"},
		},
	},
	asm.FnGetFuncIp: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.FnGetAttachCookie: {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.FnTaskPtRegs: {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "task"},
		},
	},
	asm.BuiltinFunc(176): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "entries"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.BuiltinFunc(177): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "fmt"},
			{Type: CType{Name: "__u32"}, Name: "fmt_size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "data"},
			{Type: CType{Name: "__u32"}, Name: "data_len"},
		},
	},
	asm.BuiltinFunc(178): {
		RetType: CType{Name: "unix_sock", Struct: true, Ptr: true},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "sk"},
		},
	},
	asm.BuiltinFunc(179): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "name"},
			{Type: CType{Name: "int"}, Name: "name_sz"},
			{Type: CType{Name: "int"}, Name: "flags"},
			{Type: CType{Name: "__u64", Ptr: true}, Name: "res"},
		},
	},
	asm.BuiltinFunc(180): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "task"},
			{Type: CType{Name: "__u64"}, Name: "addr"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_fn"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_ctx"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.BuiltinFunc(181): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "__u32"}, Name: "nr_loops"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_fn"},
			{Type: CType{Name: "void", Ptr: true}, Name: "callback_ctx"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
	asm.BuiltinFunc(182): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "s1"},
			{Type: CType{Name: "__u32"}, Name: "s1_sz"},
			{Type: CType{Name: "char", Const: true, Ptr: true}, Name: "s2"},
		},
	},
	asm.BuiltinFunc(183): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "__u32"}, Name: "n"},
			{Type: CType{Name: "__u64", Ptr: true}, Name: "value"},
		},
	},
	asm.BuiltinFunc(184): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
			{Type: CType{Name: "__u64", Ptr: true}, Name: "value"},
		},
	},
	asm.BuiltinFunc(185): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "ctx"},
		},
	},
	asm.BuiltinFunc(186): {
		RetType: CType{Name: "int"},
		Params:  []HelperParam{},
	},
	asm.BuiltinFunc(187): {
		RetType: CType{Name: "int"},
		Params: []HelperParam{
			{Type: CType{Name: "int"}, Name: "retval"},
		},
	},
	asm.BuiltinFunc(188): {
		RetType: CType{Name: "__u64"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
		},
	},
	asm.BuiltinFunc(189): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.BuiltinFunc(190): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "xdp_md", Struct: true, Ptr: true}, Name: "xdp_md"},
			{Type: CType{Name: "__u32"}, Name: "offset"},
			{Type: CType{Name: "void", Ptr: true}, Name: "buf"},
			{Type: CType{Name: "__u32"}, Name: "len"},
		},
	},
	asm.BuiltinFunc(191): {
		RetType: CType{Name: "long"},
		Params: []HelperParam{
			{Type: CType{Name: "void", Ptr: true}, Name: "dst"},
			{Type: CType{Name: "__u32"}, Name: "size"},
			{Type: CType{Name: "void", Const: true, Ptr: true}, Name: "user_ptr"},
			{Type: CType{Name: "task_struct", Struct: true, Ptr: true}, Name: "tsk"},
			{Type: CType{Name: "__u64"}, Name: "flags"},
		},
	},
}
